//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public Staff()
        {
            this.Staff_Salaries = new HashSet<Staff_Salaries>();
            this.StaffTasks = new HashSet<StaffTask>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Password { get; set; }
        public int Type { get; set; }
    
        public virtual ICollection<Staff_Salaries> Staff_Salaries { get; set; }
        public virtual ICollection<StaffTask> StaffTasks { get; set; }
    }
}
