//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffTask
    {
        public int Id { get; set; }
        public int Staff_Id { get; set; }
        public string Task { get; set; }
        public string Status { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
